name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Yarn Install
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      # Yarn Build
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
